sudo: required

services:
  - docker
language: node_js
node_js:
  - "4"
after_success:
  - "docker login -u $DOCKER_USER -p $DOCKER_PWD"
  - "docker build -t $DOCKER_USER/node-web-app ."
  - "docker push $DOCKER_USER/node-web-app"
